"""add photo_path

Revision ID: 18941361fb39
Revises: ebaaa2d5d1db
Create Date: 2023-12-03 00:32:04.358811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18941361fb39'
down_revision = 'ebaaa2d5d1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('photo_path')

    # ### end Alembic commands ###
