"""chat notification

Revision ID: 5b88811e5cec
Revises: ece5a041a186
Create Date: 2023-11-25 00:05:38.083688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b88811e5cec'
down_revision = 'ece5a041a186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'chat', ['chat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###
